# 
right_format = """$kubernetes$custom"""

[aws]
disabled = true

[docker_context]
disabled = true

[kubernetes]
disabled = false
format = '☸ $context \($namespace\)'


[vagrant]
disabled = true

[nodejs]
disabled = true


[custom.kubie]
command = 'echo "🌌"'
when = ''' test "$KUBIE_ACTIVE" = "1" '''
format = ' $output'
